name: Continuous integration
on: push

env:
  GODOT_VERSION: 3.4.2
  EXPORT_NAME: csgo-crosshairplus

jobs:
  export-windows:
    name: Export (Windows)
    runs-on: ubuntu-20.04
    container:
      image: barichello/godot-ci:3.4.2
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.4
      - name: Setup
        run: |
          mkdir -p ~/.local/share/godot/templates/
          mv /root/.local/share/godot/templates/$GODOT_VERSION.stable ~/.local/share/godot/templates/$GODOT_VERSION.stable
      - name: Export (Windows)
        run: |
          mkdir -p dist/
          godot -v --export "Windows Desktop" "dist/$EXPORT_NAME.exe"
      - name: Upload Artifact
        uses: actions/upload-artifact@v2.3.1
        with:
          name: ${{ env.EXPORT_NAME }}-windows
          path: dist

  export-macos:
    name: Export (macOS)
    runs-on: ubuntu-20.04
    container:
      image: barichello/godot-ci:3.4.2
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.4
      - name: Setup
        run: |
          mkdir -p ~/.local/share/godot/templates/
          mv /root/.local/share/godot/templates/$GODOT_VERSION.stable ~/.local/share/godot/templates/$GODOT_VERSION.stable
      - name: Export (macOS)
        run: |
          mkdir -p dist/
          godot -v --export "Mac OSX" "dist/$EXPORT_NAME.zip"
      - name: Upload Artifact
        uses: actions/upload-artifact@v2.3.1
        with:
          name: ${{ env.EXPORT_NAME }}-macos
          path: dist

  export-linux-desktop:
    name: Export (Linux Desktop)
    runs-on: ubuntu-20.04
    container:
      image: barichello/godot-ci:3.4.2
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.4
      - name: Setup
        run: |
          mkdir -p ~/.local/share/godot/templates/
          mv /root/.local/share/godot/templates/$GODOT_VERSION.stable ~/.local/share/godot/templates/$GODOT_VERSION.stable
      - name: Export (Linux)
        run: |
          mkdir -p dist/
          godot -v --export "Linux/X11" "dist/$EXPORT_NAME.x86_64"
      - name: Upload Artifact
        uses: actions/upload-artifact@v2.3.1
        with:
          name: ${{ env.EXPORT_NAME }}-linux-desktop
          path: dist
